name: chatbot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy=1.18
  - pip
  - pytorch=1.5.0
  - elasticsearch=7.7
  - pip:
    - tqdm==4.46
    - termcolor==1.1
    - colorama==0.4
    - torch==1.5.0
    - transformers==2.11